#!/bin/bash
#chmod u+x setup
sudo apt-get update
sudo apt-get install git -y
sudo apt-get install vim -y
sudo apt-get install python3 -y
sudo apt-get install virtualbox -y
sudo apt-get install vagrant -y
sudo apt-get install kicad -y
sudo apt-get install build-essential -y
sudo apt-get install python-pip -y
sudo pip install virtualenv -y
sudo apt-get install build-essential -y

touch .vimrc
echo "set smartindent
set tabstop=4
set shiftwidth=4
set expandtab

set number
set numberwidth=2
set colorcolumn=78
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

autocmd FileType make setlocal noexpandtab" > .vimrc

#chrome
:'
sudo apt-get install libxss1 -y
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome*.deb
rm google-chrome-stable_current_amd64.deb
'

#set up launcher
gsettings set com.canonical.Unity.Launcher favorites "['unity://running-apps', 'application://gnome-control-center.desktop', 'unity://expo-icon', 'unity://devices', 'nautilus-folder-handler.desktop']"

#workspaces
gsettings set org.compiz.core:/org/compiz/profiles/unity/plugins/core/ hsize 2
gsettings set org.compiz.core:/org/compiz/profiles/unity/plugins/core/ vsize 2

#teensyduino
sudo apt-get install gcc-avr avr-libc
sudo apt-get install openjdk-6-jre
wget http://www.pjrc.com/teensy/td_118/teensyduino.64bit
chmod u+x teensyduino.64bit
wget http://www.pjrc.com/teensy/49-teensy.rules
sudo cp 49-teensy.rules /etc/udev/rules.d/49-teensy.rules
chmod u+x /etc/udev/rules.d/49-teensy.rules
wget http://arduino.googlecode.com/files/arduino-1.0.5-linux64.tgz
tar -xvzf arduino-1.0.5-linux64.tgz
rm arduino-1.0.5-linux64.tgz
rm 49-teensy.rules
./teensyduino.64.bit

#puppet
:'wget https://pm.puppetlabs.com/cgi-bin/download.cgi?ver=latest&dist=ubuntu&arch=amd64&rel=12.04
tar
'


#for adobe, heroku, and spotify, follow the instructions on the website








